version: "3.9"

services:
  fraud-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fraud_api
    ports:
      - "8000:8000"          # API accessible on localhost:8000
      - "9090:9090"          # optional: expose Prometheus metrics if needed
    volumes:
      - ./models:/app/models   # mount trained models
      - ./logs:/app/logs       # mount logs folder
    environment:
      - PYTHONUNBUFFERED=1
      - SPARK_LOCAL_IP=127.0.0.1
      - SPARK_DRIVER_MEMORY=2g
      - SPARK_WORKER_MEMORY=2g
    restart: unless-stopped
